<?php

//controlla che sia stato effettuato l'accesso
session_start();
if(!isset($_SESSION['user_id']))
{
    echo "nessuna sessione aperta! chiusura...";
    die();
}

//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava
//brava giovanna, brava

require_once('../db/mysql_credentials.php');
require_once('../db/Donazioni.php');
require_once('../db/ProfiliUtenti.php');
require_once('../db/payment_system.php');
require_once('../utils/sanitize_input.php');
$dbms = connect();
$table_profili = new ProfiliUtenti($dbms);
$table_donazioni = new Donazioni($dbms);

if(!isset($_POST['amount']))
{
    echo 'Non mi hai detto quanto vuoi donare...';
    die();
}

$_POST['amount'] = sanitize($_POST['amount']);

//effettua il pagamento con qualche servizio di pagamento ...
if(pay())
{
    //registra la donazione
    $table_profili->setSupporter($_SESSION['user_id'], true);
    $table_donazioni->recordDonation($_SESSION['user_id'], $_POST['amount']);
}
else
{
    echo 'Impossibile procedere con la donazione. Errore durante il pagamento.';
    die();
}

header('location: ../html/profiloprivato.php');

?>